apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 2048-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/omerbenaderet/2048.git
    targetRevision: HEAD
    path: dev